export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';
export const INCREMENT_FAVORITE_COUNT = 'INCREMENT_FAVORITE_COUNT';
export const DECREMENT_FAVORITE_COUNT = 'DECREMENT_FAVORITE_COUNT';
export const REQUEST_IMAGES = 'REQUEST_IMAGES';
export const FETCH_IMAGES = 'FETCH_IMAGES';
export const RECEIVE_IMAGES = 'RECEIVE_IMAGES';
export const RERENDER_COLUMNS = 'RERENDER_COLUMNS';